spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_USERNAME}
    password: ${SPRING_DATA_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  flyway:
    enabled: true
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATA_SOURCE_URL}
    user: ${SPRING_DATA_USERNAME}
    password: ${SPRING_DATA_PASSWORD}
    # locations: classpath:db/migration
    
server:
  port: ${SERVER_PORT}
  error:
    include-message: always

logging:
  file:
    name: logs/app.log
  level:
    "[org.springframework]": DEBUG
    "[org.hibernate]": DEBUG
